apiVersion: v1
kind: Service
metadata:
  name: ahmed
  labels:
    name: service-redis
    app: demo-python-app
spec:
  ports:
   - port: 6379
     targetPort: 6379
  selector:
    name: redis
    app: demo-python-app
  