apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
  - name: jenkins-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  type: LoadBalancer
status:
  loadBalancer: {}