apiVersion: v1
kind: Service
metadata:
   name: jenkins-ubuntu-slave-service
   namespace: jenkins
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: jenkins-ubuntu-slave